import { FONT_SIZE } from '../../../styles';

const PROJECT_ITEM_HEIGHT = 9.5;
const PROJECT_ITEM_MARGIN_BOTTOM = 3;

export const PROJECT_ITEM_TOTAL_HEIGHT =
  (PROJECT_ITEM_HEIGHT + PROJECT_ITEM_MARGIN_BOTTOM) * FONT_SIZE;

export const PROJECT_ITEM_HEIGHT_VALUE = `${PROJECT_ITEM_HEIGHT}rem`;
export const PROJECT_ITEM_MARGIN_BOTTOM_VALUE = `${PROJECT_ITEM_MARGIN_BOTTOM}rem`;
